# Generated by Django 4.0.5 on 2022-06-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, verbose_name='User Name')),
                ('email_field', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=250)),
                ('owner', models.IntegerField(default=1, verbose_name='List Owner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120, verbose_name='Item Name')),
                ('item_date', models.DateTimeField(verbose_name='Item date')),
                ('desciption', models.TextField(blank=True)),
                ('owner', models.IntegerField(blank=True, default=1, verbose_name='Item Owner')),
                ('todolist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.todolist')),
            ],
        ),
    ]
